[package]
name = "regexer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
log = "0.4.29"
onlyargs = "0.2.0"
onlyargs_derive = "0.2.0"
regex = "1.12.2"
simple_logger = { version = "5.1.0", default-features = false, features = ["colors"] }
